# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_cvdl2023_hw2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QLabel
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QWidget, QVBoxLayout
from PyQt5.QtGui import QPainter, QPen, QColor
from PyQt5.QtWidgets import QVBoxLayout, QHBoxLayout
from PyQt5.QtGui import QImage
from PyQt5.QtCore import QPoint



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonLoadImage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoadImage.setGeometry(QtCore.QRect(20, 150, 113, 32))
        self.pushButtonLoadImage.setObjectName("pushButtonLoadImage")
        self.pushButtonLoadVideo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoadVideo.setGeometry(QtCore.QRect(20, 210, 113, 32))
        self.pushButtonLoadVideo.setObjectName("pushButtonLoadVideo")

        #Q1
        self.groupBackgroundSubtraction = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBackgroundSubtraction.setGeometry(QtCore.QRect(150, 50, 191, 80))
        self.groupBackgroundSubtraction.setObjectName("groupBackgroundSubtraction")
        self.pushButtonBackgroundSubtraction = QtWidgets.QPushButton(self.groupBackgroundSubtraction)
        self.pushButtonBackgroundSubtraction.setGeometry(QtCore.QRect(0, 30, 191, 32))
        self.pushButtonBackgroundSubtraction.setObjectName("pushButtonBackgroundSubtraction")

        #Q2
        self.groupOpticalFlow = QtWidgets.QGroupBox(self.centralwidget)
        self.groupOpticalFlow.setGeometry(QtCore.QRect(150, 180, 191, 80))
        self.groupOpticalFlow.setObjectName("groupOpticalFlow")
        self.pushButtonPreprocessing = QtWidgets.QPushButton(self.groupOpticalFlow)
        self.pushButtonPreprocessing.setGeometry(QtCore.QRect(2, 20, 181, 32))
        self.pushButtonPreprocessing.setObjectName("pushButtonPreprocessing")
        self.pushButtonVideoTracking = QtWidgets.QPushButton(self.groupOpticalFlow)
        self.pushButtonVideoTracking.setGeometry(QtCore.QRect(2, 50, 181, 32))
        self.pushButtonVideoTracking.setObjectName("pushButtonVideoTracking")


        #Q3
        self.groupPCA = QtWidgets.QGroupBox(self.centralwidget)
        self.groupPCA.setGeometry(QtCore.QRect(150, 310, 191, 71))
        self.groupPCA.setObjectName("groupPCA")
        self.pushButtonImageReconstruction = QtWidgets.QPushButton(self.groupPCA)
        self.pushButtonImageReconstruction.setGeometry(QtCore.QRect(0, 30, 191, 31))
        self.pushButtonImageReconstruction.setObjectName("pushButtonImageReconstruction")

        # Q4
        # 創建 MNIST GroupBox 並將水平布局應用到其中
        self.groupVGG19 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupVGG19.setGeometry(QtCore.QRect(360, 0, 600, 350))
        self.groupVGG19.setObjectName("groupVGG19")
       
        self.pushButtonPredict = QtWidgets.QPushButton(self.groupVGG19)
        self.pushButtonPredict.setGeometry(QtCore.QRect(0, 100, 91, 32))
        self.pushButtonPredict.setObjectName("pushButtonPredict")
        self.pushButtonShowModelStructure = QtWidgets.QPushButton(self.groupVGG19)
        self.pushButtonShowModelStructure.setGeometry(QtCore.QRect(0, 30, 171, 32))
        self.pushButtonShowModelStructure.setObjectName("pushButtonShowModelStructure")
        self.pushButtonShowAccuracyanLoss = QtWidgets.QPushButton(self.groupVGG19)
        self.pushButtonShowAccuracyanLoss.setGeometry(QtCore.QRect(0, 70, 181, 32))
        self.pushButtonShowAccuracyanLoss.setObjectName("pushButtonShowAccuracyanLoss")

         # #繪圖部分  創建清除按鈕
        self.pushButtonReset = QtWidgets.QPushButton(self.groupVGG19)
        self.pushButtonReset.setGeometry(QtCore.QRect(0, 130, 81, 32))
        self.pushButtonReset.setObjectName("clear")
        self.pushButtonReset.setText("Clear")       

        self.textArea1 = QtWidgets.QLabel(self.groupVGG19)
        self.textArea1.setGeometry(QtCore.QRect(10, 180, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.textArea1.setFont(font)
        self.textArea1.setText("")
        self.textArea1.setTextFormat(QtCore.Qt.AutoText)
        self.textArea1.setAlignment(QtCore.Qt.AlignCenter)
        self.textArea1.setObjectName("textArea1")


         # #繪圖部分  創建儲存按鈕
        self.paintWidget = HandwritingBoard()
        self.layoutForMNIST = QHBoxLayout()
        self.layoutForMNIST.addStretch()
        self.layoutForMNIST.addWidget(self.paintWidget)
        self.pushButtonReset.clicked.connect(self.paintWidget.clearBoard)       
        self.pushButtonPredict.clicked.connect(self.paintWidget.save)      
        self.groupVGG19.setLayout(self.layoutForMNIST)

        #Q5
        self.groupResNet50 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupResNet50.setGeometry(QtCore.QRect(360, 400, 650, 241))
        self.groupResNet50.setObjectName("groupResNet50")

        self.pushButtonLoadImage_1 = QtWidgets.QPushButton(self.groupResNet50)
        self.pushButtonLoadImage_1.setGeometry(QtCore.QRect(0, 20, 113, 32))
        self.pushButtonLoadImage_1.setObjectName("pushButtonLoadImage_1")

        self.pushButtonShowImages = QtWidgets.QPushButton(self.groupResNet50)
        self.pushButtonShowImages.setGeometry(QtCore.QRect(0, 50, 131, 32))
        self.pushButtonShowImages.setObjectName("pushButtonShowImages")

        self.pushButtonShowModelStructure_2 = QtWidgets.QPushButton(self.groupResNet50)
        self.pushButtonShowModelStructure_2.setGeometry(QtCore.QRect(0, 80, 181, 32))
        self.pushButtonShowModelStructure_2.setObjectName("pushButtonShowModelStructure_2")

        self.pushButtonShowComparsion = QtWidgets.QPushButton(self.groupResNet50)
        self.pushButtonShowComparsion.setGeometry(QtCore.QRect(0, 110, 161, 32))
        self.pushButtonShowComparsion.setObjectName("pushButtonShowComparsion")

        self.pushButtonInference = QtWidgets.QPushButton(self.groupResNet50)
        self.pushButtonInference.setGeometry(QtCore.QRect(0, 140, 113, 32))
        self.pushButtonInference.setObjectName("pushButtonInference")

        self.label = QtWidgets.QLabel(self.groupResNet50)
        self.label.setGeometry(QtCore.QRect(10, 180, 60, 16))
        self.label.setText("")
        self.label.setObjectName("label")

        self.graphicsView = QtWidgets.QLabel(self.groupResNet50)
        self.graphicsView.setGeometry(QtCore.QRect(200, 20, 200, 200))
        self.graphicsView.setObjectName("graphicsView")
        # self.scene = QtWidgets.QGraphicsScene(self.groupResNet50)
        # self.graphicsView.setScene(self.scene)
        self.textArea = QtWidgets.QLabel(self.groupResNet50)
        self.textArea.setGeometry(QtCore.QRect(420, 80, 150, 41))
        self.textArea.setObjectName("textArea")

        # self.textArea1 = QtWidgets.QLabel(self.groupVGG19)
        # self.textArea1.setGeometry(QtCore.QRect(10, 180, 30, 30))
        # font = QtGui.QFont()
        # font.setFamily("Consolas")
        # font.setPointSize(16)
        # self.textArea1.setFont(font)
        # self.textArea1.setText("")
        # self.textArea1.setTextFormat(QtCore.Qt.AutoText)
        # self.textArea1.setAlignment(QtCore.Qt.AlignCenter)
        # self.textArea1.setObjectName("textArea1")


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonLoadImage.setText(_translate("MainWindow", "Load Image"))
        self.pushButtonLoadVideo.setText(_translate("MainWindow", "Load Video"))
        # Q1
        self.groupBackgroundSubtraction.setTitle(_translate("MainWindow", "1.Background Subtraction"))
        self.pushButtonBackgroundSubtraction.setText(_translate("MainWindow", "1.Background Subtraction"))
        self.groupOpticalFlow.setTitle(_translate("MainWindow", "2.Optical Flow"))

        # Q2
        self.pushButtonPreprocessing.setText(_translate("MainWindow", "2.1Preprocessing"))
        self.pushButtonVideoTracking.setText(_translate("MainWindow", "2.2Video tracking"))


        # Q3
        self.groupPCA.setTitle(_translate("MainWindow", "3.PCA"))
        self.pushButtonImageReconstruction.setText(_translate("MainWindow", "3.Dimension Reduction"))

        # Q4
        self.groupVGG19.setTitle(_translate("MainWindow", "4.MNIST Classifier Using VGG19"))
        self.pushButtonShowModelStructure.setText(_translate("MainWindow", "1.Show Model Structure"))
        self.pushButtonShowAccuracyanLoss.setText(_translate("MainWindow", "2.Show Accuracy an Loss"))
        self.pushButtonPredict.setText(_translate("MainWindow", "3.Predict"))
        self.pushButtonReset.setText(_translate("MainWindow", "4.Reset"))

        # Q5
        self.groupResNet50.setTitle(_translate("MainWindow", "5.RestNet50"))
        self.pushButtonLoadImage_1.setText(_translate("MainWindow", "Load Image"))
        self.pushButtonShowImages.setText(_translate("MainWindow", "5.1Show Images"))
        self.pushButtonShowModelStructure_2.setText(_translate("MainWindow", "5.2Show Model Structure"))
        self.pushButtonShowComparsion.setText(_translate("MainWindow", "5.3Show Comparsion"))
        self.pushButtonInference.setText(_translate("MainWindow", "5.4 Inference"))

#繪圖部分
class HandwritingBoard(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        self.setFixedSize(350, 350)
        self.setStyleSheet("background-color: black;")
        self.image = QPixmap(350, 350)
        self.image.fill(Qt.black)
        self.lastPoint = QPoint()

    def paintEvent(self, event):
        painter = QPainter(self)
        painter.drawPixmap(self.rect(), self.image)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.lastPoint = event.pos()

    def mouseMoveEvent(self, event):
        if event.buttons() and Qt.LeftButton:
            painter = QPainter(self.image)
            pen = QPen(QColor("white"), 20, Qt.SolidLine, Qt.RoundCap, Qt.RoundJoin)
            painter.setPen(pen)
            painter.drawLine(self.lastPoint, event.pos())
            self.lastPoint = event.pos()
            self.update()

    def save(self):
        # 保存寫字板的內容為圖片
        self.image.save("Q4/handwrite.png")
    
    def clearBoard(self):
        self.image.fill(Qt.black)
        self.update()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
